modLoader = "javafml"
loaderVersion = "[39,)"
license = "MIT License"
issueTrackerURL = "https://bumblecat.dev/issues/bumlecore"

[[mods]]
    modId = "bumblecore"
    version = "${file.jarVersion}"
    displayName = "Bumblecore"
    updateJSONURL = "https://bumblecat.dev/version/bumblecore"
    displayURL = "https://bumblecat.dev/"
    logoFile = "bumblecat.png"
    credits = "Betty Boop for her stunning performance."
    authors = "Baijson"
    description = '''

    Yes. This is a library mod.


    Go, Go, Power Ninja Fried Llama!?
    '''

[[dependencies.bumblecore]]
    modId = "forge"
    mandatory = true
    versionRange = "[39,)"
    ordering = "NONE"
    side = "BOTH"